#!/usr/bin/python
import sys
import socket

from pyvisaserver.instrumentmanager import RemoteInstrument

HOST = sys.argv[1]
PORT = int(sys.argv[2])

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
resource_name = 'ASRL/dev/ttyUSB1::INSTR'
instrument_name = 'bk_1686B'
sock.connect((HOST, PORT))

bk = RemoteInstrument(instrument_name, sock, resource_name=resource_name)
bk.init()
while True:
    print(bk.query('GETS'))
